[project]
name = "sfguide-getting-started-with-openflow-spcs"
version = "0.1.0"
description = "Snowflake Quickstart for Openflow SPCS "
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
